### ISSUE TITLE
请教: 有的应用获取不到选中的文本, 比如微信, 是要怎么做才可以呢

### ISSUE THREAD

**Issue by jackple** [yetone/node-get-selected-text#3]
如视频:

https://github.com/yetone/node-get-selected-text/assets/6183232/f9536342-db2a-43b7-8c8d-acfc888e5431

**Comment by yetone** [comment]
最新版已修复此问题

**Comment by jackple** [comment]
已经下载最新版, 还是如此, 是不是我的mac有的必要的配置没到位? 求解惑

**Comment by jackple** [comment]
视频里面有几个应用能正常响应应该是因为我用了另外一个包: [node-selection](https://github.com/lujjjh/node-selection) ; 我刚刚重启过电脑, 就全部应用都不响应了, 包括chrome等

**Comment by yetone** [comment]
<img width="548" alt="image" src="https://github.com/yetone/node-get-selected-text/assets/1206493/33cc6be1-97ee-4e4a-bc64-f9d3e45ec81e">

本地测了一下，是可以的

**Comment by yetone** [comment]
https://github.com/yetone/node-get-selected-text/assets/1206493/2a1e6ed7-2218-481d-a2ae-3fe0dce8fdf2

**Comment by jackple** [comment]
直接`node`执行是可以了, 那就是没支持`electron`, 我的锅

**Comment by yetone** [comment]
你再检查一下你用的版本，应该与是否使用 electron 没有关系

**Comment by jackple** [comment]
我确认过版本是`0.1.9`了, 二进制文件的包也是
```
{
  "name": "node-get-selected-text-darwin-arm64",
  "repository": {
    "url": "https://github.com/yetone/node-get-selected-text"
  },
  "version": "0.1.9",
  "os": [
    "darwin"
  ],
  "cpu": [
    "arm64"
  ],
  "main": "node-get-selected-text.darwin-arm64.node",
  "files": [
    "node-get-selected-text.darwin-arm64.node"
  ],
  "license": "MIT",
  "engines": {
    "node": ">= 10"
  }
}
```

**Comment by yetone** [comment]
感觉你是没有提前获取 accessibility 权限导致的：https://github.com/yetone/node-get-selected-text#macos

**Comment by jackple** [comment]
![image](https://github.com/yetone/node-get-selected-text/assets/6183232/9d4367be-8ba0-41bf-b3bc-a0f0e8b568ea)

权限是有的

**Comment by yetone** [comment]
你的不是一个 electron app 吗？为什么是 vscode？

**Comment by jackple** [comment]
因为是用vscode的`运行和调试`模式去跑, 我也打包成dmg了, xx-alpha就是, 但是也一样

**Comment by jackple** [comment]
好像是跟某些东西冲突了, 有可能是`uiohook-napi`

**Comment by chenyang222** [comment]
@jackple 怎么样 解决了吗 我现在也是mac下没用   单独就行 用uiohook-napi就凉

**Comment by jackple** [comment]
> [@jackple](https://github.com/jackple) 怎么样 解决了吗 我现在也是mac下没用 单独就行 用uiohook-napi就凉

@chenyang222 没有解决, 哥们有方案么
